name: SyncGitee
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Sync Github to Gitee with white list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/funnyzak
          dst: gitee/funnyzak
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'server-ops'
          force_update: true
          clone_style: ssh
          debug: true
